import express from "express";
import { getCart,addToCart,updateCart,removeFromCart,clearCart } from "../controllers/Cart.controller.js";
import { verifyToken}  from "../Middleware/verifyToken.middle.js";
const router=express.Router();
router.get("/",verifyToken,getCart);
router.post ("/add",verifyToken,addToCart);
router.put("/update",verifyToken,updateCart);
router.delete("/clear",verifyToken,clearCart);
router.delete("/remove",verifyToken,removeFromCart);
export default router;